# Generated by Django 5.0.3 on 2024-03-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2000)),
                ('description', models.TextField(blank=True)),
                ('label', models.CharField(max_length=30)),
            ],
        ),
    ]
