# Generated by Django 5.0.3 on 2024-03-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_alter_waste_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='label',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
